# Theme settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

# Site settings
title: DROO.FOO
description: DROO.FOO
baseurl: ""
url: "https://api.droo.foo"

# Build settings
markdown: kramdown
include:
  - "**/*.md"
  - "**/*.markdown"

# Theme overrides
sass:
  style: compressed
