---
- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0644'
  notify: Restart Grafana

- name: Enable Grafana service
  systemd:
    name: grafana-server
    enabled: yes

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started

- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
  when: false
  listen: Restart Grafana
