---
- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Configure Grafana
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana

- name: Enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true

- name: Start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
