---
galaxy_info:
  author: DROO AMOR
  description: MinIO object storage deployment for blockchain data
  company: axol.io
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - minio
    - storage
    - blockchain
    - s3
    - object
    - cloud
    - distributed

dependencies: []
