---
- name: Download Prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: '0755'

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: true

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yaml
    owner: root
    group: root
    mode: '0644'

- name: Create Prometheus systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: restarted
