---
- name: Deploy MinIO on Blockchain API Server
  hosts: blockchain_api_servers
  become: true
  vars:
    minio_version: "{{ minio_version }}"
    minio_user: "{{ minio_user }}"

  roles:
    - role: minio
      vars:
        minio_version: "{{ minio_version }}"
        minio_user: "{{ minio_user }}"
        minio_group: "{{ minio_group }}"
        minio_volumes: "{{ minio_volumes }}"
        minio_opts: "{{ minio_opts }}"

    - role: grafana

  pre_tasks:
    - name: Ensure system is up to date
      apt:
        update_cache: true
        upgrade: dist

    - name: Install NTP for time synchronization
      apt:
        name: ntp
        state: present

    - name: Disable conflicting services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - mlocate
        - auditd
        - fstrim

  post_tasks:
    - name: Install Prometheus node exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
