---
- name: Deploy MinIO
  hosts: minio_servers
  become: true

  roles:
    - role: minio
    - role: prometheus
    - role: grafana

  pre_tasks:
    - name: Ensure system is up to date
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Disable conflicting services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - mlocate
        - auditd
        - fstrim
