minio_version: "{{ minio_version }}"
minio_user: "{{ minio_user }}"
minio_group: "{{ minio_group }}"
minio_volumes: "{{ minio_volumes }}"
minio_opts: "{{ minio_opts }}"
minio_root_user: "{{ minio_root_user }}"
minio_root_password: "{{ minio_root_password }}"
minio_directories: "{{ minio_directories }}"
