---
- name: Create MinIO directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'
  loop: "{{ minio_directories }}"

- name: Create SSL certificates directory if SSL is enabled
  ansible.builtin.file:
    path: "{{ minio_ssl_certificate | dirname }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'
  when: minio_enable_ssl | default(false)

- name: Deploy MinIO default configuration file
  ansible.builtin.template:
    src: minio.default.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd service file
  ansible.builtin.template:
    src: minio.service.j2
    dest: /usr/lib/systemd/system/minio.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Generate SSL certificates if enabled and not already created
  ansible.builtin.command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout {{ minio_ssl_key }}
    -out {{ minio_ssl_certificate }}
    -subj '/CN={{ minio_domain }}'
  args:
    creates: "{{ minio_ssl_certificate }}"
  when: minio_enable_ssl | default(false) and minio_ssl_certificate is defined and minio_ssl_key is defined
